services:
  db_rental:
    image: postgres
    container_name: db_rental
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_rental
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=tester
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rental
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/user/app
    links:
      - db_rental
    depends_on:
      - db_rental

volumes:
  pgdata:
    driver: local
